---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  roles_path: "test/integration/roles"
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  client_rb:
     environment: skynet_localdev
platforms:
  - name: chef12
    driver:
      customize:
        memory: 2048
        cpus: 2
      vm_hostname: default-chef12
      box: oel71-default
    transport:
      max_ssh_sessions: 1
    provisioner:
      require_chef_omnibus: 12.19.36
suites:
  - name: default
    verifier:
      name: inspec
    run_list:
      - recipe[skynet_kitchen_helper::uek4]
      - recipe[skynet::etcd]
      - recipe[skynet::kubernetes_master]
      - recipe[skynet::kubernetes_worker]
      - role[etcd-kitchen-ssl]
      - role[kube-master-kitchen-ssl]

